// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBU1Y7GjpjsAvC2vo9Ue3D9aSHBVm94-4',
    appId: '1:646399778464:web:fda172cac8ce4c86f433c5',
    messagingSenderId: '646399778464',
    projectId: 'maslive',
    authDomain: 'maslive.firebaseapp.com',
    storageBucket: 'maslive.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnnn...',
    appId: '1:1234567890:android:abcd1234',
    messagingSenderId: '1234567890',
    projectId: 'maslive',
    storageBucket: 'maslive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnnn...',
    appId: '1:1234567890:ios:abcd1234',
    messagingSenderId: '1234567890',
    projectId: 'maslive',
    storageBucket: 'maslive.appspot.com',
    iosBundleId: 'com.example.masslive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnnn...',
    appId: '1:1234567890:macos:abcd1234',
    messagingSenderId: '1234567890',
    projectId: 'maslive',
    storageBucket: 'maslive.appspot.com',
    iosBundleId: 'com.example.masslive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnnn...',
    appId: '1:1234567890:windows:abcd1234',
    messagingSenderId: '1234567890',
    projectId: 'maslive',
    storageBucket: 'maslive.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDnnn...',
    appId: '1:1234567890:linux:abcd1234',
    messagingSenderId: '1234567890',
    projectId: 'maslive',
    storageBucket: 'maslive.appspot.com',
  );
}
