include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - _archive/**
    - tooling/**
    - "lib/_legacy/**"
    - "**/*.old"
    - "**/*_legacy.dart"
    - "**/*_backup.dart"
    - "**/*_redirect.dart"
    - "lib/pages/admin_dashboard_page_REMOVED.dart"
