name: masslive
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web: ^1.1.1
  mapbox_maps_flutter: ^2.20.0
  http: ^1.1.0
  flutter_compass: ^0.8.0
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  cloud_functions: ^6.0.7
  firebase_analytics: ^12.1.3
  firebase_storage: ^13.1.0
  firebase_messaging: ^16.1.2
  geolocator: ^14.0.0
  timeago: ^3.7.0
  flutter_stripe: ^12.0.0
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  permission_handler: ^12.0.0
  image: ^4.3.0
  flutter_image_compress: ^2.3.0
  file_picker: ^11.0.2
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.3
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.0
  purchases_flutter:
    path: ../third_party/purchases_flutter
  intl: ^0.20.2
  get: ^4.7.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  pointer_interceptor: ^0.10.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  provider: ^6.1.2
  fl_chart: ^1.2.0
  share_plus: ^12.0.0
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.13.0
  hive_ce_generator: ^1.11.1
  firebase_auth_mocks: ^0.15.1
  fake_cloud_firestore: ^4.1.0+1
  mock_exceptions: ^0.8.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/textures/
    - assets/map_styles/google_light.json
    - assets/images/
    - assets/shop/
  fonts:
    - family: MASLIVEBrushV2
      fonts:
        - asset: assets/fonts/MASLIVEBrushV2.ttf
